const fs = require('fs');
const path = require('path');

const REGISTRY_FILE = path.join(__dirname, '..', 'registry.json');
const ARCHITECTURE_FILE = path.join(__dirname, '..', 'ARCHITECTURE.md');

function buildDocs() {
    console.log('Generating ARCHITECTURE.md from registry...');
    
    if (!fs.existsSync(REGISTRY_FILE)) {
        console.error('Error: registry.json not found.');
        process.exit(1);
    }

    const registry = JSON.parse(fs.readFileSync(REGISTRY_FILE, 'utf8'));

    let md = `# Antigravity Kit Architecture (Code-Enforced)\n\n`;
    md += `> Automatically generated from \`registry.json\` on ${registry.last_updated}.\n> **DO NOT EDIT THIS FILE MANUALLY.**\n\n---\n\n`;

    md += `## 📋 Overview\n\n`;
    md += `- **${registry.metadata.total_agents} Core Agents** - Enforced by \`orchestrator.js\`\n`;
    md += `- **${registry.metadata.total_skills} Active Skills** - Loaded in runtime\n`;
    md += `- **${registry.metadata.total_workflows} Workflows** - Slash command procedures\n\n---\n\n`;

    md += `## 🤖 Core Agents\n\n`;
    md += `| Agent | Role | Capabilities | Allowed Skills |\n`;
    md += `| ----- | ---- | ------------ | -------------- |\n`;
    
    for (const [agentName, profile] of Object.entries(registry.agents)) {
        md += `| \`${agentName}\` | **${profile.role}** | ${profile.capabilities.join(', ')} | ${profile.allowed_skills.join(', ')} |\n`;
    }

    md += `\n---\n\n## 🧩 Active Skills (${Object.keys(registry.skills).length})\n\n`;
    md += Object.keys(registry.skills).map(s => `- \`${s}\``).join('\n') + '\n';

    md += `\n---\n\n## 🔄 Workflows (${Object.keys(registry.workflows).length})\n\n`;
    md += Object.keys(registry.workflows).map(w => `- \`/${w}\``).join('\n') + '\n';

    md += `\n---\n\n## ⚙️ Enforcement Scripts\n\n`;
    md += `- \`orchestrator.js\`: Parses intent and routes to correct agent & skills.\n`;
    md += `- \`load-skill.js\`: Validates and idempotently syncs skills from Library to Runtime.\n`;
    md += `- \`build-registry.js\`: Re-generates the single source of truth.\n`;
    md += `- \`build-docs.js\`: Ensures this architecture document never drifts from reality.\n`;

    fs.writeFileSync(ARCHITECTURE_FILE, md);
    console.log('ARCHITECTURE.md updated successfully. Doc drift eliminated.');
}

buildDocs();
